### ISSUE TITLE
Blog HTML  - stary charset

### ISSUE THREAD

**Issue by zapalagrzegorz** [Comandeer/comandeers-tutorials#17]
> <p>To króciutkie obsługuje nawet IE6. Zdziwieni? A powinni, bo ta składnia powstała z… błędu. Na wielu stronach bowiem można było znaleźć potworka typu</p>
<pre><code class="language-markup">&lt;meta http-equiv=&quot;Content-type&quot; content=&quot;text/html;charset=&quot;UTF-8&quot;&quot;&gt;
</code></pre>
> <p>Przeglądarki stwierdziły bowiem, że nie ma sensu parsować nieprawidłowego znacznika i po prostu znalazły inny sposób: szukały czegoś na wzór <code>charset=[&quot;]*[a-z0-9][&quot;]*</code> (mam nadzieję, że to dobre wyrażenie regularne…). No i tak już zostało, a później to… <a href="https://www.w3.org/TR/html50/infrastructure.html#extracting-character-encodings-from-meta-elements" rel="noreferrer noopener">ustandaryzowano w ramach HTML5</a>. ...

Czemu potworkiem/ nieprawidłowym znacznikiem było (jest):
<pre><code class="language-markup">&lt;meta http-equiv=&quot;Content-type&quot; content=&quot;text/html;charset=&quot;UTF-8&quot;&quot;&gt;
</code></pre>
?

**Comment by Comandeer** [comment]
Z powodu dodatkowych, niepotrzebnych cudzysłowów wokół `UTF-8`.
