### ISSUE TITLE
Array

### ISSUE THREAD

**Issue by drrak** [Comandeer/comandeers-tutorials#31]
Cześć Comandeer,
czy byłbyś tak miły i wytłumaczył mi, albo opisał to w swoim poradniku, jak stworzyć taką planszę:
https://drrak.github.io/peg-solitaire/
używając Array i obrazków? Nie mam pojęcia jak się do tego zabrać. Zastanawiam się też jak potem zidentyfikować pozycję każdego pionka.

Pozdrawiam

**Comment by Comandeer** [comment]
Hej, mógłbyś mi posłać maila w tej sprawie? Issues na GH nie są zbyt dobrym miejscem na taką rozmowę.
